apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pfnd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pfnd
    app.kubernetes.io/part-of: byoc-app-rmoc
  name: pfnd
spec:
  rules:
  - host: pfnd-byoc-rnom-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-g7b6s.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: pfnd
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
